version: "3.7"
services:
  sweete:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        user: hung
        uid: 1000
    image: sweete-img
    container_name: sweete-container
    restart: unless-stopped
    working_dir: /var/www/
    ports:
      - "8000:9000"
    volumes:
      - ./:/var/www/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
