version: "3.7"
services:
  sweete:
    build:
      args:
        user: hung
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: sweete-img
    container_name: sweete-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www/
    networks:
      - sweete-network
  db:
    image: mysql:8.0
    container_name: sweete-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - sweete-network
networks:
  sweete-network:
    driver: bridge
